### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by ianmicheal** [histat/OpenLara-dc#1]
Hi , I'm use to kos not libronin and i cant find any FAQ or HOW TO on how to build it, I did try my self but there is little info on libronin how to setup or build the toolchain .

**Comment by ianmicheal** [comment]
dogbox2@dogbox2-PC /opt/toolchains/ronin-src
$ make
rm -rf include
mkdir include
mkdir include/ronin
mkdir include/lwip
mkdir include/netif
mkdir include/arch
for h in cdfs.h common.h dc_time.h gddrive.h gfxhelper.h gtext.h maple.h matrix.
h misc.h notlibc.h report.h ronin.h serial.h sincos_rroot.h soundcommon.h sound.
h ta.h translate.h video.h vmsfs.h; do ln -s -f ../../$h include/ronin/; done
ln -s -f ../zlib/zlib.h ../zlib/zconf.h include/
ln -s -f ../lwipopts.h include/
cd include/lwip && ln -s -f ../../lwip/include/lwip/*.h ./
cd include/lwip && ln -s -f ../../lwip/include/ipv4/lwip/*.h ./
cd include/netif && ln -s -f ../../lwip/include/netif/*.h ./
cd include/netif && ln -s -f ../../lwip/arch/dc/include/netif/*.h ./
cd include/arch && ln -s -f ../../lwip/arch/dc/include/arch/*.h ./
sh-elf-as -little crt0.s -o lib/crt0.o
make: sh-elf-as: Command not found
make: *** [Makefile:90: lib/crt0.o] Error 127

I know this means 127 not found i have 2 working kos toolchains that work correct what I'm i missing also have all libronin precompiled and src but it does the same as above

**Comment by histat** [comment]
add PATH your toolchains.

**Comment by megavolt85** [comment]
> add PATH your toolchains.

what is version gcc and libronin used?
dc_hardware.c -> pvr_set_bg_color -> ta_bg_list not found

**Comment by histat** [comment]
gcc 4.8.5 I used at least c++11 support.
I modified libronin 
current on gitlab there
try
git clone -b develop https://gitlab.com/histat/libronin.git

**Comment by ianmicheal** [comment]
Thank you :)

**Comment by ianmicheal** [comment]
I had done all this

> 1) launch a terminal

2) add the /bin paths to your elf & arm compilers, eg:
export PATH=$PATH:/opt/toolchains/dc/sh-elf/bin:/opt/toolchains/dc/arm-eabi/bin

(you can see your path with the command: echo $PATH

3) if your arm compiler is arm-eabi* like me (ie, arm compiler generated via the latest kos), add the following symbolic links inside your arm bin folder:
eg for me:
from within the folder /opt/toolchains/dc/arm-eabi/bin:
ln -s arm-eabi-as arm-elf-as
ln -s arm-eabi-ar arm-elf-ar
ln -s arm-eabi-gcc arm-elf-gcc
ln -s arm-eabi-objcopy arm-elf-objcopy

(or you can modify the names of the executables in the libronin makefile of course)

4) be sure that pike is installed, if not run something like: sudo apt-get install pike8.0

5) rename the function itoa to itoaronin in following files:
report.c
report.h
vmsfs.c (9 instances to modify)
examples/ex_vmsfscheck.c

6) launch make from the main libronin folder to generate libronin.a

7) launch make from the /libmad folder to generate libmad.a

8) if later you want to use libronin's functionality to send a program via serial to the dreamcast, be sure to modify these references in the Makefile:
replace all references to: /home/peter/hack/dreamsnes/dc/
into: ./tools/ (eg: /home/peter/hack/dreamsnes/dc/ipupload.pike would become ./tools/ipupload.pike

9) same as 8), if you want to use ipupload.pike, you need to modify the 1st line of /tools/ipupload.pike:
change
#!/usr/local/bin/pike
into
#!/usr/bin/env pike

10) Remove any references to those 2 examples from the main Makefile, since these examples do not exist anymore:
examples/ex_purupuru
examples/ex_compress

11) Add those 2 examples in the main makefile, since they are not foreseen yet:
examples/ex_control
examples/ex_clouds

12) to compile an example with serial output (this generates an .elf file, eg for example ex_video.c):
make examples/ex_video.elf

13) to compile an example without serial output (this generates a .bin file, eg for example ex_video.c):
(I think you need to modify 1 line in the main Makefile: TYPE = elf <- change elf to bin.
I think they wanted to make it work just by letting the user change the extension of the example in the command line, but this does not seem to work - it linked the file with libronin.a, not libronin-noserial.a)
make examples/ex_video.bin



This resulted in a succesful compilation, I didn't check it by running examples or so

>

**Comment by ianmicheal** [comment]
error: 'struct ta_buffers' does not contain an element named 'ta_zclip';

**Comment by ianmicheal** [comment]
seems new version does not show any textures on hardware did you test it on hardware works on emulators like demul but not hardware megavolt got it all to compile

**Comment by megavolt85** [comment]
> 

libronin -> ta.c
regs[0x088/4] = 0x3e4cccc0 /* zclip */;
it's don't work on real hardware, only in emulator
displayed only HUD
if change to regs[0x088/4] = 0 /* zclip */; all fine
